version: 3.0.0.{build}
branches:
  only:
  - develop
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: DryWetMidi.Benchmarks\bin\Release\BenchmarkDotNet.Artifacts\results\*.json
  name: Benchmarks results
skip_commits:
  files:
    - '**/*.md'